language: python

python:
  - "3.6"

before_install:
  - export PYTHONPATH=$HOME/builds/DragonStuff/Aller
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django --quiet

script:
  - sudo apt-cache policy sqlite3
  - sudo apt-get install sqlite3=3.8.1-1ubuntu3
  - python Aller/manage.py migrate --run-syncdb
