language: python

before_install:
  - export PYTHONPATH=$HOME/builds/DragonStuff/Aller
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django --quiet

script:
  - python manage.py syncdb --noinput
