language: python
dist: xenial

python:
  - "3.6"

before_install:
  - export PYTHONPATH=$HOME/builds/DragonStuff/Aller
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django --quiet

script:
  - python Aller/manage.py migrate --run-syncdb
