# Generated by Django 2.0.3 on 2018-05-04 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body_type', models.CharField(max_length=100)),
                ('price_per_unit', models.PositiveIntegerField()),
                ('unit_size', models.CharField(choices=[('DA', 'Daily'), ('WE', 'Weekly'), ('MO', 'Monthly'), ('YR', 'Yearly')], default='DA', max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=30)),
                ('plate', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=3)),
                ('registered_owner', models.CharField(max_length=30)),
                ('transmission', models.BooleanField()),
                ('condition', models.CharField(max_length=30)),
                ('kilometers', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('seats', models.PositiveSmallIntegerField()),
                ('doors', models.PositiveSmallIntegerField()),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('image_url', models.URLField()),
                ('listing_type', models.CharField(max_length=2)),
                ('is_rented', models.BooleanField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('converted_longitude', models.CharField(max_length=30)),
                ('converted_latitude', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=30)),
                ('rating', models.PositiveSmallIntegerField()),
                ('address', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllerNow.Location'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllerNow.Person'),
        ),
    ]
