# Generated by Django 2.0.3 on 2018-05-04 11:10

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0002_auto_20180504_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='user__username'),
        ),
    ]
