# Generated by Django 2.0.3 on 2018-05-15 08:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0003_auto_20180504_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('carchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllerNow.Car')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='paycardexpiry',
            field=models.TextField(default='12/20', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='paycardname',
            field=models.CharField(default='JOHN SMITH', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='paycardnumber',
            field=models.CharField(default='1234 1234 1234 1234', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='personpaying',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllerNow.Person'),
        ),
    ]
