# Generated by Django 2.0.3 on 2018-05-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0005_car_credit_aud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='credit_aud',
        ),
    ]
