# Generated by Django 2.0.3 on 2018-05-20 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0008_auto_20180520_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
