# Generated by Django 2.0.3 on 2018-05-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0009_auto_20180520_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='carchoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AllerNow.Car'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='personpaying',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AllerNow.Person'),
        ),
    ]
