# Generated by Django 2.0.3 on 2018-05-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0012_auto_20180520_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='personpaying',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllerNow.Person'),
        ),
    ]
