# Generated by Django 2.0.3 on 2018-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0016_auto_20180520_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
