# Generated by Django 2.0.3 on 2018-05-23 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllerNow', '0018_auto_20180520_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='datefrom',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='payment',
            name='dateto',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_to',
            field=models.DateField(default=datetime.date(2018, 5, 24)),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(default='/static/images/pic01.jpg'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_rented',
            field=models.CharField(default='notyet', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_type',
            field=models.CharField(default='NEW', max_length=2),
        ),
    ]
